### PR TITLE
Use issue form to report build errors and update PR template

### PR DESCRIPTION
**Pull request by tobiasdiez**
Can be seen at https://github.com/tobiasdiez/sage/issues/new?assignees=&labels=build%2Ct%3Abug&template=failure-building-from-source.yml&title=%3Ctitle%3E

### CODE REVIEW

**Review by mkoeppe — APPROVED** [review]

**Comment by mkoeppe** [comment]
Hi Tobias, could you resolve the conflict please?

**Comment by tobiasdiez** [comment]
Will do, but can you please sync this "fork" first with the main repo so that all of these unrelated commits here also disappear.

**Comment by mkoeppe** [comment]
done

**Comment by tobiasdiez** [comment]
thanks! conflicts are resolved now

**Comment by mkoeppe** [comment]
My files duplicate some of this - please feel free to send PRs to clean it up. I can't work on it this week

**Pull request merged**
